# Generated by Django 4.1.3 on 2022-12-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0005_remove_detail_foodtype_detail_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Reg_No',
            field=models.CharField(choices=[('CST/17/SWE/00041', 'CST/17/SWE/00041'), ('CST/17/SWE/00021', 'CST/17/SWE/00021'), ('CST/17/SWE/00055', 'CST/17/SWE/00055'), ('CST/17/SWE/00056', 'CST/17/SWE/00056'), ('CST/17/SWE/00043', 'CST/17/SWE/00043'), ('CST/17/SWE/00049', 'CST/17/SWE/00049')], max_length=30),
        ),
    ]
